### ISSUE TITLE
How to use your library if I do not extend a FragmentActivity?

### ISSUE THREAD

**Issue by isabsent** [eltos/SimpleDialogFragments#16]
I am trying to adopt your lib for my project in which I need to show some dialogs in the android.app.Activity **but not the FragmentActivity**.

        SimpleListDialog.build()
                .title(R.string.dialog_title_attention)
                .choiceMode(SimpleListDialog.SINGLE_CHOICE_DIRECT)
                .items(getBaseContext(), new int[]{R.string.choice_A, R.string.choice_B, R.string.choice_C})
                .show(???????????????????, SimpleListDialog.class.getName());
What should I write at the first argument of the `show` method?

**Comment by eltos** [comment]
I recommend that you use `AppCompatActivity` from the support-library (which my library relies on) instead of `android.app.Activity`. This will also allow you to use newer features and material design on older android versions. It extends the core `android.app.Activity`, thus you should be able to just replace it without any compatibility issues to your existing code. You only need to change the `getFragmentManager()` calls to `getSupportFragmentManager()` in case you are using it.


`android.app.Activity`
↳`android.support.v4.app.FragmentActivity`
     ↳`android.support.v7.app.AppCompatActivity`

**Comment by eltos** [comment]
Any update on this @isabsent ?

**Comment by eltos** [comment]
I think it is much easier for you to change to the support library (i.e. adding functionality) instead of me trying to make the library work without it (i.e. removing functionality). I don't think rewriting the library is that simple and I will not spend time on this (I don't have much free time momentarly anyways and if you don't want to change existing code then why would I change the whole library?).
However, it seems that you already put some effort into this. So please feel free to continue your Work; I will happily accept a merge request if you find a propper solution.

Concerning your last question:
Yes, that is exactly what happens here. You might want to check the api-level and call this function only on devices running 17+.

**Comment by isabsent** [comment]
I have ended with this code:

            while (!handled && resultFragment != null){
                if (Build.VERSION.SDK_INT > Build.VERSION_CODES.JELLY_BEAN) {
                    if (resultFragment instanceof OnDialogResultListener) {
                        handled = ((OnDialogResultListener) getTargetFragment())
                                .onResult(getTag(), which, extras);
                    }
                    resultFragment = resultFragment.getParentFragment();
                } else {
                    Toast.makeText(getActivity(), "Do not use this fork of SimpleDialogFragment library from a Fragment if API < 17!", Toast.LENGTH_LONG).show();
                }
            }
for `android.app.Activity` and `android.app.Fragment`instead of `support` classes.

**Comment by eltos** [comment]
You do realise that this is an infinite loop on devices running API<17 and will not even call the target fragments `onResult` method, don't you?

**Comment by isabsent** [comment]
Thanks! Fixed by means of `break;` :)
